# Default values for nmstate
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
nmstate:
  name: kubernetes-nmstate-operator
  namespace: openshift-nmstate
  channel: stable
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  operatorGroupName: openshift-nmstate
  targetNamespaces: # Target namespaces for namespace-scoped operators
    - openshift-nmstate
  
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# nmstate<bool>: 'true' or 'false' - Controls whether nmstate is managed
#
# Configuration:
# nmstate-subscription-name<string>: Operator subscription name (default: 'kubernetes-nmstate-operator')
# nmstate-channel<string>: Operator channel (default: 'stable')
# nmstate-version<string>: Specific operator version (CSV) to install (optional)
# nmstate-source<string>: Operator catalog source (default: 'redhat-operators')
# nmstate-source-namespace<string>: Catalog namespace (default: 'openshift-marketplace')
#
# Examples:
# autoshift.io/nmstate: 'true'
# autoshift.io/nmstate-subscription-name: 'kubernetes-nmstate-operator'
# autoshift.io/nmstate-channel: 'stable'
# autoshift.io/nmstate-version: 'operator-name.v1.x.x'
# autoshift.io/nmstate-source: 'redhat-operators'
# autoshift.io/nmstate-source-namespace: 'openshift-marketplace'