# Default values for far
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
far:
  name: far-operator
  namespace: openshift-workload-availability
  channel: stable
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  operatorGroupName: openshift-workload-availability
  # targetNamespaces: # Optional: specify target namespaces for namespace-scoped operators
  #   - openshift-workload-availability
  
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# far<bool>: 'true' or 'false' - Controls whether far is managed
#
# Configuration:
# far-subscription-name<string>: Operator subscription name (default: 'far-operator')
# far-channel<string>: Operator channel (default: 'stable')
# far-version<string>: Specific operator version (CSV) to install (optional)
# far-source<string>: Operator catalog source (default: 'redhat-operators')
# far-source-namespace<string>: Catalog namespace (default: 'openshift-marketplace')
#
# Examples:
# autoshift.io/far: 'true'
# autoshift.io/far-subscription-name: 'far-operator'
# autoshift.io/far-channel: 'stable'
# autoshift.io/far-version: 'operator-name.v1.x.x'
# autoshift.io/far-source: 'redhat-operators'
# autoshift.io/far-source-namespace: 'openshift-marketplace'