# Default values for node-healthcheck
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
nodeHealthcheck:
  name: node-healthcheck-operator
  namespace: openshift-workload-availability
  channel: stable
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  operatorGroupName: node-healthcheck-operator-group
  
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# node-healthcheck<bool>: 'true' or 'false' - Controls whether node-healthcheck is managed
#
# Configuration:
# node-healthcheck-subscription-name<string>: Operator subscription name (default: 'node-healthcheck-operator')
# node-healthcheck-channel<string>: Operator channel (default: 'stable')
# node-healthcheck-version<string>: Specific operator version (CSV) to install (optional)
# node-healthcheck-source<string>: Operator catalog source (default: 'redhat-operators')
# node-healthcheck-source-namespace<string>: Catalog namespace (default: 'openshift-marketplace')
#
# Examples:
# autoshift.io/node-healthcheck: 'true'
# autoshift.io/node-healthcheck-subscription-name: 'node-healthcheck-operator'
# autoshift.io/node-healthcheck-channel: 'stable'
# autoshift.io/node-healthcheck-version: 'operator-name.v1.x.x'
# autoshift.io/node-healthcheck-source: 'redhat-operators'
# autoshift.io/node-healthcheck-source-namespace: 'openshift-marketplace'
