# Default values for remediations.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# machine-config-motd<bool>: 'true' or 'false' - Enable manual remediation policies (default: 'false')
#
# Note: This policy applies manual security and compliance remediations including:
# - Configuring allowed image registries (registry.redhat.io, quay.io by default)
# - Removing samples operator for security compliance
# These are manual remediations that require explicit enablement
#
# Examples:
# autoshift.io/machine-config-motd: 'true'
