# Default values for mtv
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
mtv:
  name: mtv-operator
  namespace: openshift-mtv
  channel: release-v2.10
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  operatorGroupName: openshift-mtv
  targetNamespaces: # Target namespaces for namespace-scoped operators
    - openshift-mtv
  
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# mtv<bool>: 'true' or 'false' - Controls whether mtv is managed
#
# Configuration:
# mtv-subscription-name<string>: Operator subscription name (default: 'mtv-operator')
# mtv-channel<string>: Operator channel (default: 'release-v2.10')
# mtv-version<string>: Specific operator version (CSV) to install (optional)
# mtv-source<string>: Operator catalog source (default: 'redhat-operators')
# mtv-source-namespace<string>: Catalog namespace (default: 'openshift-marketplace')
#
# Examples:
# autoshift.io/mtv: 'true'
# autoshift.io/mtv-subscription-name: 'mtv-operator'
# autoshift.io/mtv-channel: 'release-v2.10'
# autoshift.io/mtv-version: 'operator-name.v1.x.x'
# autoshift.io/mtv-source: 'redhat-operators'
# autoshift.io/mtv-source-namespace: 'openshift-marketplace'